### PR TITLE
Code style updates

### PR DESCRIPTION
**Pull request by jensengillett**
-Removed unnecessary extra files that were lying around.
-Fixed up code based on proper PEP guidelines.
-Added a check for email length based on https://tools.ietf.org/html/rfc3696#section-3
@MiningMark48 - please check that I didn't make any stupid mistakes and delete a file you added that was being used.
@aabuelazm - please verify that docker deploy still works properly, and merge the changes downstream.
Let me know when you've reviewed the changes, and I'll merge to the main branch.

### CODE REVIEW

**Review by MiningMark48 — APPROVED** [review]
Everything looks good, ran code, all seems well on my end. 

The file deletions should be fine. They were likely files that got added when I was working on the database system way-back-when that never got removed (user data was likely left in case it was ever needed, reactors was probably an accident).

I recommend a second look at the Docker stuff from @aabuelazm. I'm _mostly_ sure it's fine, but I don't _know_ Docker.

**Review by aabuelazm — APPROVED** [review]
Seems good on my end.

**Comment by MiningMark48** [comment]
**Reminder:** This begins hashing emails. Make sure to convert existing emails file to their hashed counterparts before running using the [util script](https://github.com/jensengillett/verificationbot/blob/development/hasher_util.py)!

**Comment by jensengillett** [comment]
Changes confirmed to work, merging request.

**Pull request merged**
