### PR TITLE
Change JSON Config to TOML Config 

### PR DESCRIPTION
**Pull request by MiningMark48**
TOML is debatably a better format for a config, as it is better organized and allows comments, making it more legible to a third-party user that may not know what they're looking at. 

This PR switches the JSON config system to the TOML config system.

I have created a utility _config.py_ file for storing a default TOML config, creating a config when none is found, and for, of course, reading the toml config.

The only required module is _toml_.

### CODE REVIEW

**Review by jensengillett — CHANGES_REQUESTED** [review]
Revert bot.py to use tabs instead of spaces

**Comment by MiningMark48** [comment]
Reformatted for tabs, re-requested review.

**Review by jensengillett — APPROVED** [review]

**Comment by jensengillett** [comment]
Could you update the readme.md with the new changes to setup?

**Comment by MiningMark48** [comment]
@jensengillett Updated README

**Pull request merged**
